version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NovaNest-front
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
