version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NovaNest-front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DJANGO_HOST_URL=https://back.novanestventure.com
      - MAIN_APP_URL=https://www.NovaNestVenture.com
      - DATABASE_URL=postgresql://postgres:12345@localhost:5432/landa?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
